### ISSUE TITLE
OSP queens use /etc/tempest/tempest.conf instead of /etc/redhat-certification-openstack/tempest.conf

### ISSUE THREAD

**Issue by sjabasti** [redhat-cip/ansible-role-openstack-certification#14]
The role will install redhat-certification which in turn will create /etc/rhcert.xml. No proxy information will be configured in it. My suggestion is to be able to pass proxies as variables to this role

**Comment by fcharlier** [comment]
Why does it need proxy configuration ?

**Comment by fcharlier** [comment]
Are the directions given in https://github.com/redhat-cip/dci-openstack-agent/blob/master/README_advanced.md#how-to-set-http-proxy-for-my-dci-openstack-agent sufficient ?

**Comment by sjabasti** [comment]
This role is called from red hat DCI openstack agent. Our DCI agent is hidden behind corporate proxies.  The directions help install red hat certification but do not change the rhcert xml. If you open rhcert you will notice:

    <catalog-url search-retries="3" search-timeout="10"></catalog-url>
    
    
    
    
  </urls>

**Comment by sjabasti** [comment]
I have changed to title as this is not the root cause of the issue i currently have (my apologies i created the issue a bit to quick). However I still believe these proxy values should still be set by this ansible role.

**Comment by sjabasti** [comment]
So think i was completely wrong as i thought it was downloading the test list from red hat servers. This is not the case, so i am sorry about my mistake. However I think i found the root cause of my problem:

the error:

```
2019-10-11 11:07:31.721 3330 INFO tempest [-] Using tempest config file /etc/tempest/tempest.conf


Trying to fetch the list of tempest tests via command:
Could not fetch the list of tempest tests via command so falling back to local file.
Error: Exception raised in test openstack/cinder_volumes:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rhcert/client/harness.py", line 1260, in runTest
    rv = test.run()
  File "/usr/lib/python2.7/site-packages/rhcert/suites/openstack_cert/cinder.py", line 52, in run
    result.combine(subtest.run())
  File "/usr/lib/python2.7/site-packages/rhcert/test.py", line 565, in run
    self.result = self.runSubTest()
  File "/usr/lib/python2.7/site-packages/rhcert/suites/openstack_cert/cinder.py", line 63, in runSubTest
    return a.run(self.test)
  File "/usr/lib/python2.7/site-packages/rhcert/suites/openstack_cert/common.py", line 699, in run
    result.combine(self.pre_run(test))
  File "/usr/lib/python2.7/site-packages/rhcert/suites/openstack_cert/common.py", line 527, in pre_run
    self.map_apis_to_tests()
  File "/usr/lib/python2.7/site-packages/rhcert/suites/openstack_cert/common.py", line 593, in map_apis_to_tests
    self.get_tempest_tests_list_via_cmd())
  File "/usr/lib/python2.7/site-packages/rhcert/suites/openstack_cert/tempest_tests.py", line 56, in get_tempest_mapped_tests
    self.tempest_test_list = self.get_tests_list()
  File "/usr/lib/python2.7/site-packages/rhcert/suites/openstack_cert/tempest_tests.py", line 29, in get_tests_list
    self.tests_dict = self.get_tests_dict()
  File "/usr/lib/python2.7/site-packages/rhcert/suites/openstack_cert/tempest_tests.py", line 24, in get_tests_dict
    self.tests_dict = json.load(tests_file)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

So after some searching, it appears that the role copies tempest.conf to /etc/redhat-certification-openstack/tempest.conf. However the certification uses /etc/tempest.conf, so the command to list the tests(ie tempest run -l ) fails.


I also found that there is a bug report on it https://bugzilla.redhat.com/show_bug.cgi?id=1628403

**Comment by sjabasti** [comment]
Is there a solution to this problem?

**Comment by fcharlier** [comment]
@sjabasti well, either certification team fixes their tool to match [their documentation](https://access.redhat.com/documentation/en-us/red_hat_openstack_certification/1.0/html/red_hat_openstack_certification_workflow_guide/certification_tests#running-certs-implementing-openstack-apis) which states that the file should be placed in `/etc/redhat-certification-openstack/` or we can workaround this issue by copying the `tempest.conf` file in both folders to be sure.

What do you think ?

**Comment by sjabasti** [comment]
While I do like the idea that the certification team fixes their tool, I think that it will take a long time before it is fixed ( the issue I mentioned dates from 2018). So I suggest the workaround as the timeline until it works will be shorter. Note that the workaround should be taken out when the cert tool is fixed.

**Comment by sjabasti** [comment]
@fcharlier Can you fix it? Softwarefactory throws an error when trying to create a http password and I am having some corporate proxy issues with git over ssh.

**Comment by apevec** [comment]
> Softwarefactory throws an error when trying to create a http password

@sjabasti off-topic here, but if you have more details please report it in https://tree.taiga.io/project/morucci-software-factory/issues
Thanks!
