### ISSUE TITLE
test_config: malformed json

### ISSUE THREAD

**Issue by dsavineau** [redhat-cip/ansible-role-openstack-certification#7]
Since https://github.com/redhat-cip/ansible-role-openstack-certification/commit/d08dad1a40c40746646ef7c5a9eba794758916b3 the comma at the end of the last line didn't have been removed.
This results with a python trace during tempest_config test :
```
$ sudo rhcert-ci run --test tempest_config
(...)
Checking the creation of tempest.conf under /etc/redhat-certification-openstack ...
Error: Exception raised in test openstack/tempest_config:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rhcert/client/harness.py", line 1063, in runTest
    rv = test.run()
  File "/usr/lib/python2.7/site-packages/rhcert/suites/openstack_cert/test_tempest_config.py", line 135, in run
    self.run_interactive_test()
  File "/usr/lib/python2.7/site-packages/rhcert/suites/openstack_cert/test_tempest_config.py", line 85, in run_interactive_test
    end_point = self.get_endpoint_conf()
  File "/usr/lib/python2.7/site-packages/rhcert/suites/openstack_cert/test_tempest_config.py", line 74, in get_endpoint_conf
    test_config = json.load(fp)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 7 column 1 (char 1034)
```

This can be verified with jq command :
```
$ jq . /etc/redhat-certification-openstack/test_config.json
parse error: Expected another key-value pair at line 7, column 1
```

**Comment by goneri** [comment]
Maybe the file is just empty?
